#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_SEL4PX4)        += px4

# list of libraries the app needs to build
px4-y = common libsel4 libmuslc libsel4vka libcpio libelf libsel4allocman \
        libsel4platsupport libsel4platsupport libsel4muslcsys libsel4test \
        libsel4simple libsel4vspace libsel4utils libutils

# set up correct simple lib for our kernel
ifdef CONFIG_KERNEL_STABLE
px4-$(CONFIG_LIB_SEL4_SIMPLE_STABLE) += libsel4simple-stable
else
px4-$(CONFIG_LIB_SEL4_SIMPLE_DEFAULT) += libsel4simple-default
endif

# add the tests app  as a component so that we can elf load it
#px4-components-y += sel4px4-tests
px4-components = $(addprefix $(STAGE_BASE)/bin/, $(px4-components-y))

px4: export COMPONENTS=${px4-components}
px4: ${px4-components-y} kernel_elf $(px4-y)
